version: "3.2"
services:


  nginx:
    image: nginx:latest
    domainname: localhost
    ports:
      - "80:80"
    volumes:
      - ./:/fulltest
      - ./dist/docker/nginx/main.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    hostname: fulltest.dev
    networks:
      - fulltest_net

  php:
    build: ./dist/docker/php/
    volumes:
      - ./:/fulltest
      - ./dist/docker/php/fulltest.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - mysql
    networks:
      - fulltest_net

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=fulltest
      - MYSQL_PASSWORD=fulltest
      - MYSQL_DATABASE=fulltest
      - TZ=Europe/Moscow
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "mysqlsocks:/var/run/mysqld/"
      - ./dist/cache/mysql:/var/lib/mysql/
      - "./dist/docker/mysql/fulltest.cnf:/etc/mysql/conf.d/fulltest.cnf"
    networks:
      - fulltest_net

volumes:
  mysqlsocks: {}

networks:
  fulltest_net:
    driver: bridge
